name: Build, Push, and Deploy Carpooling Service

on:
  push:
    paths:
      - 'carpooling-service/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/carpooling-service:latest ./carpooling-service

    - name: Push Docker image
      run: docker push ${{ secrets.DOCKER_USERNAME }}/carpooling-service:latest

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-south-1  

    - name: Set up kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: 'latest'

    - name: Update kubeconfig
      run: aws eks update-kubeconfig --region ap-south-1 --name connectplus-cluster

    
    - name: Deploy to EKS
      run: |
        kubectl apply -f ./k8s/carpooling-service-deployment.yaml
