name: Build and Push Carpooling Service

on:
  push:
    paths:
      - 'carpooling-service/**'    

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/carpooling-service:latest ./carpooling-service

    - name: Push Docker image
      run: docker push ${{ secrets.DOCKER_USERNAME }}/carpooling-service:latest
