name: Roommate Finder Service CI/CD

on:
  push:
    paths:
      - 'roommate-finder-service/**'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Docker Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/roommate-finder-service:latest ./roommate-finder-service

      - name: Push Docker Image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/roommate-finder-service:latest
